tasks:
  - before: |
      VERSION="16.16.0" \
      && source $HOME/.nvm/nvm.sh \
      && nvm install $VERSION \
      && nvm use $VERSION \
      && nvm alias default $VERSION
  - init: npm install && npm run build
    command: npm run start